# and commit this file to your remote git repository to share the goodness with others.

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

# https://www.gitpod.io/docs/references/gitpod-yml

tasks:
  - init: npm install
    command: npm run dev

ports:
  - port: 5173
    onOpen: open-browser



vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true


